# vim:ft=ansible:
---

- name: Create terragrunt directory
  file:
    path: "/opt/terragrunt-{{ terragrunt_version }}"
    state: directory
    owner: "root"
    group: "root"
  register: terragrunt_directory

- name: Download terragrunt
  get_url:
    url: "{{ terragrunt_download_url }}"
    dest: "/opt/terragrunt-{{ terragrunt_version }}/terragrunt"

- name: Make terragrunt executable
  file:
    path: "/opt/terragrunt-{{ terragrunt_version }}/terragrunt"
    mode: 0755

- name: Adding terragrunt command to user path
  file:
    src: "/opt/terragrunt-{{ terragrunt_version }}/terragrunt"
    dest: /usr/bin/terragrunt
    state: link
