---
jenkins_version: "2.89.2"
jenkins_deb_pkg: "jenkins_{{ jenkins_version|mandatory }}_all.deb"

jenkins_user:         jenkins
jenkins_group:        "{{ jenkins_user }}"
jenkins_home:         /var/lib/jenkins
jenkins_plugins_dir: "{{ jenkins_home }}/plugins"
jenkins_admin_username:   admin
jenkins_admin_password:

jenkins_helper_scripts_dir:    "{{ jenkins_home }}/scripts"
jenkins_post_init_scripts_dir: "{{ jenkins_home }}/init.groovy.d"

jenkins_args:
  - "--webroot=/var/cache/$NAME/war"
  - "--httpPort=$HTTP_PORT"
jenkins_http_port:      "8080"
jenkins_ajp_port:       "-1"
jenkins_java_args:      []
jenkins_max_open_files: 8192
jenkins_executors: 3

jenkins_apt_pkgs_extra: []
jenkins_pip_pkgs_extra: []
